version: '3.9.15'
services:
  frontend:
    container_name: frontend
    #image: codingchallenge-frontend
    build:
      context: frontend/.
      dockerfile: Dockerfile
    volumes:
      - './frontend/src:/app/src'
      - './frontend/public:/app/public'
    #  - './frontend/node_modules:/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - WATCHPACK_POLLING=true
  backend:
    container_name: backend
    #image: codingchallenge-frontend
    build:
      context: microservices/currency-processor/.
      dockerfile: Dockerfile
    volumes:
      - './microservices/currency-processor/src:/app/src'
    ports:
      - 3001:3001